apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1 #mínimo de replicas
  maxReplicas: 2 #máxmio de replicas
  targetCPUUtilizationPercentage: 10