apiVersion: v1
kind: ReplicationController
metadata:
  name: ej2-rc
  labels:
    app: ej2
    type: front-end

# Acá se indica el pod a usar
spec:
  template:
    metadata:
      name: ej2-pod
      labels:
        app: ej2
        type: front-end

    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2